// <auto-generated />
using System;
using MangaManagement.DataAccess.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaManagementSystem.DataAccess.Migrations
{
    [DbContext(typeof(MangaDbContext))]
    [Migration("20260603081434_ChangeUserStatusToBool")]
    partial class ChangeUserStatusToBool
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Annotation", b =>
                {
                    b.Property<Guid>("AnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ManuscriptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageNo")
                        .HasColumnType("int");

                    b.Property<decimal>("PositionX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PositionY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("AnnotationId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ChapterPageId");

                    b.HasIndex("ManuscriptId");

                    b.ToTable("Annotations", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Chapter", b =>
                {
                    b.Property<Guid>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ChapterNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmissionDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.HasKey("ChapterId");

                    b.HasIndex("SeriesId", "ChapterNo")
                        .IsUnique();

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.ChapterPage", b =>
                {
                    b.Property<Guid>("ChapterPageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImageFileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ManuscriptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageNo")
                        .HasColumnType("int");

                    b.HasKey("ChapterPageId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ImageFileAssetId");

                    b.HasIndex("ManuscriptId", "PageNo")
                        .IsUnique();

                    b.ToTable("ChapterPages", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", b =>
                {
                    b.Property<Guid>("FileAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ObjectPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FileAssetId");

                    b.HasIndex("ObjectPath")
                        .IsUnique();

                    b.HasIndex("UploadedBy");

                    b.ToTable("FileAssets", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", b =>
                {
                    b.Property<Guid>("ManuscriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Feedback")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("PreviewFileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SourceFileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("ManuscriptId");

                    b.HasIndex("PreviewFileAssetId");

                    b.HasIndex("SourceFileAssetId");

                    b.HasIndex("ChapterId", "VersionNo")
                        .IsUnique();

                    b.ToTable("Manuscripts", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.PageTask", b =>
                {
                    b.Property<Guid>("PageTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssistantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ManuscriptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageEnd")
                        .HasColumnType("int");

                    b.Property<int>("PageStart")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PageTaskId");

                    b.HasIndex("AssistantId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ManuscriptId");

                    b.ToTable("PageTasks", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.PageTaskSubmission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PageTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubmittedFileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId");

                    b.HasIndex("SubmittedFileAssetId");

                    b.HasIndex("PageTaskId", "VersionNo")
                        .IsUnique();

                    b.ToTable("PageTaskSubmissions", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Series", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MangakaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TantouEditorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SeriesId");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.UserAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AssignmentId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId")
                        .IsUnique()
                        .HasFilter("[Status] = 1");

                    b.ToTable("UserAssignments", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Annotation", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Author")
                        .WithMany("Annotations")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.ChapterPage", "ChapterPage")
                        .WithMany("Annotations")
                        .HasForeignKey("ChapterPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", "Manuscript")
                        .WithMany("Annotations")
                        .HasForeignKey("ManuscriptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ChapterPage");

                    b.Navigation("Manuscript");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Chapter", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Series", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.ChapterPage", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Chapter", "Chapter")
                        .WithMany("ChapterPages")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", "ImageFileAsset")
                        .WithMany()
                        .HasForeignKey("ImageFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", "Manuscript")
                        .WithMany("ChapterPages")
                        .HasForeignKey("ManuscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("ImageFileAsset");

                    b.Navigation("Manuscript");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Uploader")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Chapter", "Chapter")
                        .WithMany("Manuscripts")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", "PreviewFileAsset")
                        .WithMany()
                        .HasForeignKey("PreviewFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", "SourceFileAsset")
                        .WithMany()
                        .HasForeignKey("SourceFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chapter");

                    b.Navigation("PreviewFileAsset");

                    b.Navigation("SourceFileAsset");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.PageTask", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Assistant")
                        .WithMany("AssignedPageTasks")
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Chapter", "Chapter")
                        .WithMany("PageTasks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", "Manuscript")
                        .WithMany("PageTasks")
                        .HasForeignKey("ManuscriptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assistant");

                    b.Navigation("Chapter");

                    b.Navigation("Manuscript");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.PageTaskSubmission", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.PageTask", "PageTask")
                        .WithMany("Submissions")
                        .HasForeignKey("PageTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", "SubmittedFileAsset")
                        .WithMany()
                        .HasForeignKey("SubmittedFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PageTask");

                    b.Navigation("SubmittedFileAsset");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.User", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.UserAssignment", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "FromUser")
                        .WithMany("AssignmentsFromUser")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "ToUser")
                        .WithMany("AssignmentsToUser")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Chapter", b =>
                {
                    b.Navigation("ChapterPages");

                    b.Navigation("Manuscripts");

                    b.Navigation("PageTasks");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.ChapterPage", b =>
                {
                    b.Navigation("Annotations");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("ChapterPages");

                    b.Navigation("PageTasks");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.PageTask", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Series", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.User", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("AssignedPageTasks");

                    b.Navigation("AssignmentsFromUser");

                    b.Navigation("AssignmentsToUser");

                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
