// <auto-generated />
using System;
using MangaManagement.DataAccess.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaManagementSystem.DataAccess.Migrations
{
    [DbContext(typeof(MangaDbContext))]
    partial class MangaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Annotation", b =>
                {
                    b.Property<Guid>("AnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ManuscriptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageNo")
                        .HasColumnType("int");

                    b.Property<decimal>("PositionX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PositionY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("AnnotationId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ManuscriptId");

                    b.ToTable("Annotations", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.BoardDecision", b =>
                {
                    b.Property<Guid>("BoardDecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("VotingDeadline")
                        .HasColumnType("datetime2");

                    b.HasKey("BoardDecisionId");

                    b.HasIndex("SeriesId");

                    b.ToTable("BoardDecisions", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.BoardVote", b =>
                {
                    b.Property<Guid>("BoardVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("BoardDecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VoteValue")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BoardVoteId");

                    b.HasIndex("VoterId");

                    b.HasIndex("BoardDecisionId", "VoterId")
                        .IsUnique();

                    b.ToTable("BoardVotes", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Chapter", b =>
                {
                    b.Property<Guid>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("ChapterNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmissionDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.HasKey("ChapterId");

                    b.HasIndex("SeriesId", "ChapterNo")
                        .IsUnique();

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.ChapterPage", b =>
                {
                    b.Property<Guid>("ChapterPageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImageFileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageNo")
                        .HasColumnType("int");

                    b.HasKey("ChapterPageId");

                    b.HasIndex("ImageFileAssetId");

                    b.HasIndex("ChapterId", "PageNo")
                        .IsUnique();

                    b.ToTable("ChapterPages", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Escalation", b =>
                {
                    b.Property<Guid>("EscalationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EscalationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("SeriesId");

                    b.ToTable("Escalations", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", b =>
                {
                    b.Property<Guid>("FileAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ObjectPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FileAssetId");

                    b.ToTable("FileAssets", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GenreId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", b =>
                {
                    b.Property<Guid>("ManuscriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("ManuscriptId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("ChapterId", "VersionNo")
                        .IsUnique();

                    b.ToTable("Manuscripts", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.PageTask", b =>
                {
                    b.Property<Guid>("PageTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AssistantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ManuscriptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PageEnd")
                        .HasColumnType("int");

                    b.Property<int>("PageStart")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PageTaskId");

                    b.HasIndex("AssistantId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ManuscriptId");

                    b.HasIndex("UserId");

                    b.ToTable("PageTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_PageTasks_PageRange", "[PageStart] <= [PageEnd]");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.PageTaskSubmission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PageTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("SubmittedFileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId");

                    b.HasIndex("SubmittedFileAssetId");

                    b.HasIndex("PageTaskId", "VersionNo")
                        .IsUnique();

                    b.ToTable("PageTaskSubmissions", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.ProposalPage", b =>
                {
                    b.Property<Guid>("ProposalPageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PageNo")
                        .HasColumnType("int");

                    b.Property<Guid>("PreviewFileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProposalPageId");

                    b.HasIndex("PreviewFileAssetId")
                        .IsUnique();

                    b.HasIndex("SeriesId", "PageNo")
                        .IsUnique();

                    b.ToTable("ProposalPages", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.RankingSnapshot", b =>
                {
                    b.Property<Guid>("RankingSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBottom20Percent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RankNo")
                        .HasColumnType("int");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RankingSnapshotId");

                    b.HasIndex("SeriesId");

                    b.ToTable("RankingSnapshots", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Series", b =>
                {
                    b.Property<Guid>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MangakaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RankingScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("RejectReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("SourceZipFileAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SeriesId");

                    b.HasIndex("MangakaId");

                    b.HasIndex("SourceZipFileAssetId")
                        .IsUnique()
                        .HasFilter("[SourceZipFileAssetId] IS NOT NULL");

                    b.ToTable("Series", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.SeriesGenre", b =>
                {
                    b.Property<Guid>("SeriesGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeriesGenreId");

                    b.HasIndex("GenreId");

                    b.HasIndex("SeriesId", "GenreId")
                        .IsUnique();

                    b.ToTable("SeriesGenres", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.UserAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ToUserId");

                    b.HasIndex("FromUserId", "AssignmentType")
                        .IsUnique()
                        .HasFilter("[AssignmentType] = 'TantouEditor' AND [UnassignedAt] IS NULL AND [DeletedAt] IS NULL");

                    b.ToTable("UserAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserAssignments_NotSelf", "[FromUserId] <> [ToUserId]");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.UserNotification", b =>
                {
                    b.Property<Guid>("UserNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserNotificationId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId", "NotificationId")
                        .IsUnique();

                    b.ToTable("UserNotifications", (string)null);
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.VoteRecord", b =>
                {
                    b.Property<Guid>("VoteRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReaderCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VoteCount")
                        .HasColumnType("int");

                    b.HasKey("VoteRecordId");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("SeriesId");

                    b.ToTable("VoteRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_VoteRecords_Count", "[VoteCount] <= [ReaderCount]");
                        });
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Annotation", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Author")
                        .WithMany("Annotations")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", "Manuscript")
                        .WithMany("Annotations")
                        .HasForeignKey("ManuscriptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Manuscript");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.BoardDecision", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Series", "Series")
                        .WithMany("BoardDecisions")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.BoardVote", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.BoardDecision", "BoardDecision")
                        .WithMany("BoardVotes")
                        .HasForeignKey("BoardDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Voter")
                        .WithMany("BoardVotes")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoardDecision");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Chapter", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Series", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.ChapterPage", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", "ImageFileAsset")
                        .WithMany()
                        .HasForeignKey("ImageFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("ImageFileAsset");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Escalation", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Creator")
                        .WithMany("CreatedEscalations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Resolver")
                        .WithMany("ResolvedEscalations")
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Series", "Series")
                        .WithMany("Escalations")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Resolver");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Chapter", "Chapter")
                        .WithMany("Manuscripts")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Reviewer")
                        .WithMany("ReviewedManuscripts")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chapter");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.PageTask", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Assistant")
                        .WithMany("AssistantPageTasks")
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Chapter", "Chapter")
                        .WithMany("PageTasks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", "Manuscript")
                        .WithMany("PageTasks")
                        .HasForeignKey("ManuscriptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", null)
                        .WithMany("AssignedPageTasks")
                        .HasForeignKey("UserId");

                    b.Navigation("Assistant");

                    b.Navigation("Chapter");

                    b.Navigation("Manuscript");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.PageTaskSubmission", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.PageTask", "PageTask")
                        .WithMany("Submissions")
                        .HasForeignKey("PageTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", "SubmittedFileAsset")
                        .WithMany("PageTaskSubmissions")
                        .HasForeignKey("SubmittedFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PageTask");

                    b.Navigation("SubmittedFileAsset");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.ProposalPage", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", "PreviewFileAsset")
                        .WithOne("ProposalPagePreview")
                        .HasForeignKey("MangaManagementSystem.DataAccess.Entities.Models.ProposalPage", "PreviewFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Series", "Series")
                        .WithMany("ProposalPages")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PreviewFileAsset");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.RankingSnapshot", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Series", "Series")
                        .WithMany("RankingSnapshots")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Series", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Mangaka")
                        .WithMany("Series")
                        .HasForeignKey("MangakaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", "SourceZipFileAsset")
                        .WithOne("SeriesSourceZip")
                        .HasForeignKey("MangaManagementSystem.DataAccess.Entities.Models.Series", "SourceZipFileAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mangaka");

                    b.Navigation("SourceZipFileAsset");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.SeriesGenre", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Genre", "Genre")
                        .WithMany("SeriesGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Series", "Series")
                        .WithMany("SeriesGenres")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.User", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.UserAssignment", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "FromUser")
                        .WithMany("AssignmentsFromUser")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "ToUser")
                        .WithMany("AssignmentsToUser")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.UserNotification", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.VoteRecord", b =>
                {
                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.User", "Confirmer")
                        .WithMany("ConfirmedVoteRecords")
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MangaManagementSystem.DataAccess.Entities.Models.Series", "Series")
                        .WithMany("VoteRecords")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Confirmer");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.BoardDecision", b =>
                {
                    b.Navigation("BoardVotes");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Chapter", b =>
                {
                    b.Navigation("Manuscripts");

                    b.Navigation("PageTasks");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.FileAsset", b =>
                {
                    b.Navigation("PageTaskSubmissions");

                    b.Navigation("ProposalPagePreview");

                    b.Navigation("SeriesSourceZip");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Genre", b =>
                {
                    b.Navigation("SeriesGenres");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Manuscript", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("PageTasks");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.PageTask", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.Series", b =>
                {
                    b.Navigation("BoardDecisions");

                    b.Navigation("Chapters");

                    b.Navigation("Escalations");

                    b.Navigation("ProposalPages");

                    b.Navigation("RankingSnapshots");

                    b.Navigation("SeriesGenres");

                    b.Navigation("VoteRecords");
                });

            modelBuilder.Entity("MangaManagementSystem.DataAccess.Entities.Models.User", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("AssignedPageTasks");

                    b.Navigation("AssignmentsFromUser");

                    b.Navigation("AssignmentsToUser");

                    b.Navigation("AssistantPageTasks");

                    b.Navigation("BoardVotes");

                    b.Navigation("ConfirmedVoteRecords");

                    b.Navigation("CreatedEscalations");

                    b.Navigation("ResolvedEscalations");

                    b.Navigation("ReviewedManuscripts");

                    b.Navigation("Series");

                    b.Navigation("UserNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
